### ISSUE TITLE
Syntax Error in serialize

### ISSUE THREAD

**Issue by kelleyl** [clamsproject/clams-python-sdk#1]
I'm getting this syntax error when importing the serialize module. 
`  File "/usr/local/lib/python3.5/dist-packages/clams/serialize/__init__.py", line 34
    context: str
           ^
SyntaxError: invalid syntax` 

The type hints were added in this commit a997777. Does this syntax require a certain python version? I'm trying to dockerize EAST and the parent image I'm using has python 3.5.

**Comment by keighrim** [comment]
Could you try with python 3.6? I think static type declaration was introduced in 3.6. 
In the future, I'll make it work with older versions of python.

**Comment by kelleyl** [comment]
great, No errors with 3.7.

**Comment by keighrim** [comment]
okay, closing this.
