### ISSUE TITLE
Accessing data in REST API

### ISSUE THREAD

**Issue by kelleyl** [clamsproject/clams-python-sdk#3]
The data I was sending to the rest api wasn't being accessed in the api function call. request.form['data'] was empty. I added a quick fix here 43d3f49 . It looks like its possibly related to this https://stackoverflow.com/questions/10434599/get-the-data-received-in-a-flask-request.

**Comment by keighrim** [comment]
Fixed in #4, I guess. Closing the issue.

**Comment by keighrim** [comment]
...and that was a hasty decision. This needs more work to fully fixed.

**Comment by keighrim** [comment]
Fixed via #6.
